import { Geist, Geist_Mono, Manufacturing_Consent, Markazi_Text, Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "./(lander)/Header";
import CheckoutContextProvider from "@/components/context/Checkout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manufacturingConsent = Manufacturing_Consent({
  variable: "--font-manufacturing-consent",
  subsets: ['latin'],
  weight: ['400']
})

const markaziText = Markazi_Text({
  variable: "--font-markazi-text",
  subsets: ['latin'],
  weight: ['400', '500', '600']
})

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ['latin'],
  weight: ['300', '400', '500']
})

export const metadata = {
  title: "The Crier - The Premier Source of Breaking Stories According to Experts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${manufacturingConsent.variable} ${markaziText.variable} ${notoSans.variable}`}>
        <CheckoutContextProvider>
          {children}
        </CheckoutContextProvider>
      </body>
    </html>
  );
}
